### ISSUE TITLE
Bundle shows only the root node

### ISSUE THREAD

**Issue by remoteclient** [AgrosupDijon-DSI/BreadcrumbBundle#5]
Hello at all,

I hope that somebody can help me. I recently upgraded my application to symfony to version 2.7.15.
knp-menu-bundle and knp-menu are both at version 2.1.1 and cnerta/breadcrumb-bundle is on 2.1.1.

My problem is that the breadcrumbs show only the root node regardless of the route I visit.
The menus I render with knp-menu-bundle itself just show up like they should, so I think that this is not a problem with knp.

Neither cnerta_breadcrumb_get nor cnerta_breadcrumb_render give me the the full breadcrumb. A twig dump also just gives me an array with only the root node.

If anyone has an idea of debugging this issue will be welcome.

Thanks in advance.

**Comment by waldo2188** [comment]
Hy !

Take a look at this, [https://github.com/waldo2188/DemoMenu](https://github.com/waldo2188/DemoMenu).

It's in French, but you will see a full fonctionnal KnpMenuBundle and CnertaBreadcrumb working together with Symfony 2.7.15

Maybe you will find solution in it.

**Comment by remoteclient** [comment]
Thank you for your answer.
Main difference is that I use knp-menu-bundle and knp-menu are both at version 2.1.1 because Sonata Admin depends on it. Does it work with that versions too?

**Comment by wtfred** [comment]
Closed as repository will be archived
