### ISSUE TITLE
Type error: Argument 1 passed to NutritionBundle\Menu\MenuBuilder::__construct() must implement interface Knp\Menu\FactoryInterface, none given

### ISSUE THREAD

**Issue by merianos** [AgrosupDijon-DSI/BreadcrumbBundle#6]
Hello,

I am totally new on Symfony and I try to build a basic admin dashboard. Among the features I need the dashboard to have is a breadcrumb.

At the moment I have already built my menu using the `KnpMenuBundle` and works as it should.

Now I try to implement the breadcrumb using your bundle, but I get the following error:

`Type error: Argument 1 passed to NutritionBundle\Menu\MenuBuilder::__construct() must implement interface Knp\Menu\FactoryInterface, none given, called in /mnt/raid/Projects/Testings/18-jan-2018-sugar-api/vendor/knplabs/knp-menu-bundle/src/Provider/BuilderAliasProvider.php on line 130`

My current setup looks like that:

## AppKernel.php

```
<?php

// ...

class AppKernel extends Kernel {
	public function registerBundles() {
		$bundles = [
                       // ...
			new \Knp\Bundle\MenuBundle\KnpMenuBundle(),
			new \Cnerta\BreadcrumbBundle\CnertaBreadcrumbBundle(),
                       // ...
        ];
                // ...

		return $bundles;
	}

    // ...
}
```

## My Bundle `services.yml`

```
services:
  # ...
  app.menu_builder:
    class: NutritionBundle\Menu\MenuBuilder
    public: true
    arguments: [ '@knp_menu.factory']
    tags:
      - { name: knp_menu.menu_builder, method: create_main_menu, alias: main }
```

## My MenuBuilder Class

```
namespace NutritionBundle\Menu;

use Knp\Menu\FactoryInterface;

class MenuBuilder {

	private $factory;

	public function __construct( FactoryInterface $factory ) {
		$this->factory = $factory;
	}

	public function create_main_menu( array $options ) {
		$menu = $this->factory->createItem(
			'Home',
			array(
				'childrenAttributes' => array(
					'class' => 'main-nav',
					'id'    => 'main-nav',
				),
			)
		);

                // ...

		return $menu;
	}
}
```

## My Dashboard Layout File

```
<!doctype html>
<html lang="{{ app.request.locale }}">
<head>
    <!-- ... -->
</head>
<body>
<div class="page-wrapper fixed-navbar-top">
	<!-- ... -->
	{{ cnerta_breadcrumb_render('NutritionBundle:MenuBuilder:create_main_menu') }}
	<!-- ... -->
</body>
</html>
```

After a long time of searching the code, I found that the method `Knp\Bundle\MenuBundle\Provider\BuilderAliasProvider::getBuilder` in the line `130` initializing the `MenuBuilder` class using the following code:

```
$builder = new $class();
```

And this seems to be the issue. Unfortunately, I don't have any idea on how to solve that issue :( Any idea, please?

Note: This issue appears only when I use your breadcrumb bundle. The menu it is working perfectly.

**Comment by wtfred** [comment]
Closed as repository will be archived
